### ISSUE TITLE
improved accept header

### ISSUE THREAD

**Issue by gemal** [structured-data/linter#38]
the Accept header being sent from your tool is:

`application/n-triples, text/plain;q=0.5, application/n-quads, text/x-nquads, application/ld+json, application/x-ld+json, application/rdf+json, text/html;q=0.5, application/xhtml+xml;q=0.7, image/svg+xml, text/n3, text/rdf+n3, application/rdf+n3, text/turtle, text/rdf+turtle, application/turtle, application/x-turtle, application/rdf+xml, text/csv, text/tab-separated-values, application/csvm+json, application/trig, application/x-trig, application/trix, */*;q=0.1`

it seems that `text/csv` is preferred over `text/html` ?

**Comment by gkellogg** [comment]
Yes, both it, and `text/tab-separated-values` should probably be at a lower quality level. Perhaps just under `text/html` so `text/csv;q=0.4`. We can probably reduce the quality of `text/plain` as it is pretty obsolete now as an N-Triples mime-type.

But, increasingly, CSV data on the web should become increasingly semantic, which is why it's included there at all.
