### ISSUE TITLE
SDL and a Google AMP document

### ISSUE THREAD

**Issue by jaygray0919** [structured-data/linter#42]
Here's a site with JSON-LD but composed using Google AMP requirements.
  https://ontomatica.io/
SDL initially process the JSON-LD but then bails-out when it sees the `<style amp-custom>`.
Or maybe something else is going on that confuses SDL.
FYI the JSON-LD is properly parsed by Google Structured Data Testing tool (see the link in the footer).
Anything we should be doing differently to cure this problem?

/jay gray

**Comment by gkellogg** [comment]
The Linter complains because it does not think that `<style amp-custom>` is a valid tag, which is due to the underlying HTML parser [Nokogumbo](https://github.com/rubys/nokogumbo). It was not generating output due to an issue in the writer, which failed when the input was invalid. This should be fixed in version 2.4.3, which is up now.
