### ISSUE TITLE
To many Enhanced search result preview

### ISSUE THREAD

**Issue by mashutkaxxx** [structured-data/linter#83]
Hello!

I check page [https://dnevnichok.club/izmena/na-rechke/](https://dnevnichok.club/izmena/na-rechke/) my blog and your tools show 28 Enhanced search result preview. This is normal or something wrong? How to fixed it? 

[http://linter.structured-data.org/?url=https:%2F%2Fdnevnichok.club%2Fizmena%2Fna-rechke%2F](http://linter.structured-data.org/?url=https:%2F%2Fdnevnichok.club%2Fizmena%2Fna-rechke%2F)

![IMG_6201](https://github.com/user-attachments/assets/6f02c36b-67d4-450e-bafc-1147f38f076e)

Thanks for reply. 

Marry Christmas and Happy New Year!

Best Regards
Masha

**Comment by jaygray0919** [comment]
SDL does not guarantee what Google will display. Gregg is saying "You may see something like this ..."
Also, look at your `Linter Messages`; you have some clean-up work to do.
Not quite sure about this repeating string: `, , an actual search result may display other content ...`
It may be related to repeating `@types` without a unique identifier.


</body>
</html>

**Comment by gkellogg** [comment]
What @jaygray0919 is correct; the purpose of the Linter is to give some visibility into what your markup is saying as well as if you're using the vocabulary (schema.org as well as others) in a consistent way; the actual displayed results are only to support this. Google's testing tool will likely show things differently.

The bottom where it says "Raw structured data ..." attempts to give you a view of how the data lays out based on subjects referring to objects via properties. Other data shows up based upon the logical inferences made from the way you use the data.

The "Linter Messages" shows areas where your code says things that don't match expectations; not necessarily errors, but inconsistencies. For example:

    property og:url: Object "https://dnevnichok.club/izmena/na-rechke/"@ru-ru not compatible with range (ogc:url)

This means that the value is a language tagged string instead of a URL (or at least, and `go:url`).

    property schema:height: Object "696"^^<http://www.w3.org/2001/XMLSchema#integer> not compatible with rangeIncludes (schema:Distance,schema:QuantitativeValue)

Is likely fine, as you're using an integer, while schema.org expects a structured value (Distance or QuantitativeValue), which the integer could be interpreted as.

> Not quite sure about this repeating string: , , an actual search result may display other content ...
> It may be related to repeating @types without a unique identifier.

This is because the (quite old) system for displaying snippets is just indicative of what Google may show, or may have shown back when this was all new.

It may be useful to send your page through my Distiller to see it displayed in another format such as Turtle (see [here](http://rdf.greggkellogg.net/distiller?command=serialize&output_format=turtle&url=https:%2F%2Fdnevnichok.club%2Fizmena%2Fna-rechke%2F)). This is useful for seeing if the data embedded on your webpage says what you want it to say.
